const estudiante = [
    {
        id: 1,
        nombre: 'Jorge Medina Arenas',
        matricula: 'JMA09081990',
        especialidad: 'Medicina',
        semestre: 4,
        fechaNacimiento: new Date(1990, 7, 9),
    },
    {
        id: 2,
        nombre: 'Isaías Medina Arenas',
        matricula: 'IMA06071972',
        especialidad: 'Desarrollador de software',
        semestre: 8,
        fechaNacimiento: new Date(1972, 6, 7),
    },
    {
        id: 3,
        nombre: 'Yeni Ayala Jimenez',
        matricula: 'YAJ11011979',
        especialidad: 'Arquitectura',
        semestre: 5,
        fechaNacimiento: new Date(1972, 6, 7),
    },
    {
        id: 4,
        nombre: 'Yasmin Pamela Sanchez Gómez',
        matricula: 'YPSG09111997',
        especialidad: 'Criminología',
        semestre: 9,
        fechaNacimiento: new Date(1997, 10, 9),
    },
    {
        id: 5,
        nombre: 'Isaac Jacob Medina Ayala',
        matricula: 'IJMA09101993',
        especialidad: 'Desarrollador de Software',
        semestre: 12,
        fechaNacimiento: new Date(1993, 9, 9),
    },
    {
        id: 6,
        nombre: 'Yasmin Pamela Sanchez Gómez',
        matricula: 'YPSG09111997',
        especialidad: 'Criminología',
        semestre: 9,
        fechaNacimiento: new Date(1997, 10, 9),
    },
    {
        id: 7,
        nombre: 'Maria Guadalupe Ayala Jimenez',
        matricula: 'MGAJ12121971',
        especialidad: 'Administración de empresas',
        semestre: 7,
        fechaNacimiento: new Date(1971, 11, 12),
    },
    {
        id: 8,
        nombre: 'Moises Abraham Medina Ayala',
        matricula: 'MAMA05101999',
        especialidad: 'Criminología',
        semestre: 13,
        fechaNacimiento: new Date(1999, 9, 5),
    },
    {
        id: 9,
        nombre: 'Maria Elena Gomez Lincona',
        matricula: 'MEGL28041981',
        especialidad: 'Arquitectura',
        semestre: 6,
        fechaNacimiento: new Date(1981, 3, 28),
    },
    {
        id: 10,
        nombre: 'Yahir Alexander Perez Perez',
        matricula: 'YAPP04092001',
        especialidad: 'Robotica',
        semestre: 3,
        fechaNacimiento: new Date(2001, 8, 4),
    },
    {
        id: 11,
        nombre: 'Litzi Ayelen Bobadilla Mendez',
        matricula: 'LABM03022007',
        especialidad: 'Medicina',
        semestre: 5,
        fechaNacimiento: new Date(2007, 1, 3),
    },
    {
        id: 12,
        nombre: 'Leonardo Juarez Mendez',
        matricula: 'LJM08031997',
        especialidad: 'Robotica',
        semestre: 9,
        fechaNacimiento: new Date(1997, 2, 8),
    },
    {
        id: 13,
        nombre: 'Brenda Maleni Sanchez Gomez',
        matricula: 'BMSG28111992',
        especialidad: 'Derecho',
        semestre: 10,
        fechaNacimiento: new Date(1992, 10, 28),
    },
    {
        id: 14,
        nombre: 'Avril Trujillo Sanchez',
        matricula: 'ATS02042000',
        especialidad: 'Criminología',
        semestre: 12,
        fechaNacimiento: new Date(2000, 3, 2),
    },
    {
        id: 15,
        nombre: 'Sergio Trujillo Perez',
        matricula: 'STP05051990',
        especialidad: 'Desarrollo de software',
        semestre: 6,
        fechaNacimiento: new Date(1990, 4, 5),
    },
    {
        id: 16,
        nombre: 'Kimberly Ocampo Ayala',
        matricula: 'KOA10061996',
        especialidad: 'Administración de empresas',
        semestre: 13,
        fechaNacimiento: new Date(1996, 5, 10),
    }
];